[build]
  command = "npm run build" # Si es necesario ejecutar un comando de compilación antes de generar la función

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[functions]]
  directory = "functions"
  include = ["**/*"]